[package]
name = "imagedata"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
dict = "0.1.5"
log = "0.4.20"
fitsio = "0.21.2"

[dev-dependencies]
rand = "0.8.4"
